version: '3'

services:
  elasticsearch1: # Elasticsearch Instance
    container_name: elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - node.name=elasticsearch1
      - discovery.seed_hosts=elasticsearch2
      - bootstrap.memory_lock=true      
      - cluster.name=article-cluster
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"      
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      esnet:
        aliases:
          - elasticsearch
  elasticsearch2:
    container_name: elasticsearch2
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - node.name=elasticsearch2
      - discovery.seed_hosts=elasticsearch1
      - cluster.name=article-cluster
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      - bootstrap.memory_lock=true            
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      esnet:
        aliases:
          - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    container_name: kibana
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601    
    depends_on: 
      - elasticsearch1
      - elasticsearch2
    networks:
      esnet:
      

volumes:
  esdata1:  
    driver: local
  esdata2:
    driver: local

networks: 
  esnet:
    driver: bridge
